export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT_CURRENT_USER = 'LOGOUT_CURRENT_USER';
export const CLEAR_LOGIN_FORM = 'CLEAR_LOGIN_FORM';
export const SET_LOGGING_IN = 'SET_LOGGING_IN';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const SET_LOGIN_FORM_ERROR = 'SET_LOGIN_FORM_ERROR';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_LOGIN_INPUT = 'SET_LOGIN_INPUT';
