export const SET_LOADING_USER = 'SET_LOADING_USER';
export const SET_SUBMITTING_USER = 'SET_SUBMITTING_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const SET_USER_FORM = 'SET_USER_FORM';
export const SET_USER_FORM_INPUT = 'SET_USER_FORM_INPUT';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
